### ISSUE TITLE
Testing visibility

### ISSUE THREAD

**Issue by adriacidre** [joinself/issue-tracker#1]
This is testing linked issues visibility

- [ ] [An issue on android](https://github.com/joinself/self-android/issues/2102)
- [ ] [Same issue on iOS](https://github.com/joinself/self-ios/issues/963)
- [ ] [Change needed on the api](https://github.com/joinself/self-api/pull/57)
- [ ] [Something on a SDK](https://github.com/joinself/self-ruby-sdk/issues/199)

**Comment by adriacidre** [comment]
This is a comment from the internal issue tracker
